In [1]:
import numpy as np

In [2]:
np.arange(0, 10, 2)

# 0 2 4 6 8

array([0, 2, 4, 6, 8])

In [3]:
np.arange(90, 0, -5)

array([90, 85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10,
        5])

In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a[a >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
seven_to_nine_filter = ( (a >= 7) & (a <= 9))
a[seven_to_nine_filter]

array([7, 8, 9])

In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
b[0][2] = 333
b

array([[  1,   2, 333,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [14]:
a

array([[  1,   2, 333,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [15]:
b = np.array([[1, 2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [16]:
b.sum()

10

In [17]:
b.sum(axis=0) #vertically

array([4, 6])

In [18]:
b.sum(axis=1) #horizontally

array([3, 7])

In [19]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
          	[0.54627315, 0.05093587, 0.40067661, 0.55645993],
          	[0.12697628, 0.82485143, 0.26590556, 0.5691701]
])
print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.5691701 ]]


In [20]:
A.min()

0.05093587

In [21]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [22]:
A.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones( (5, 3) )

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.ones( (2, 3, 3) )

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros( (5, 3) )

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.zeros( (2, 3, 3) )

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
np.random.random(5)

array([0.85074425, 0.09724411, 0.29236023, 0.21496609, 0.19783993])